SPAWN:New('MiG-31 Opp - No Engage - 1')
    :InitKeepUnitNames(false)
    :InitLimit(2, 500)
    :InitDelayOff()
    :InitSkill("Trained")
    :InitRepeatOnLanding()
    :SpawnScheduled(600, .3)

SPAWN:New('MiG-29A Opp - No Engage - 1')
  :InitKeepUnitNames(false)
  :InitLimit(3, 500)
  :InitDelayOff()
  :InitSkill("Trained")
  :InitRepeatOnLanding()
  :SpawnScheduled(600, .3)

SPAWN:New('Su-30SM Opp - No Engage - 1')
  :InitKeepUnitNames(false)
  :InitLimit(4, 500)
  :InitDelayOff()
  :InitSkill("Trained")
  :InitRepeatOnLanding()
  :SpawnScheduled(600, .3)

SPAWN:New('Su-27 Opp - No Engage - 1')
  :InitKeepUnitNames(false)
  :InitLimit(3, 500)
  :InitDelayOff()
  :InitSkill("Trained")
  :InitRepeatOnLanding()
  :SpawnScheduled(600, .3)